"""inital migration

Revision ID: 32047b6bd4af
Revises:
Create Date: 2021-01-05 16:51:49.109961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32047b6bd4af'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('username', sa.String(
                        length=100), nullable=False),
                    sa.Column('email', sa.String(length=50), nullable=False),
                    sa.Column('hashed_password', sa.String(
                        length=255), nullable=False),
                    sa.Column('profile_pic', sa.String(
                        length=100), nullable=True),
                    sa.Column('banner', sa.String(length=100), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('email'),
                    sa.UniqueConstraint('username')
                    )
    op.create_table('followers',
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('follower', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['follower'], ['users.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
                    )
    op.create_table('products',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('sold_by', sa.Integer(), nullable=True),
                    sa.Column('name', sa.String(length=100), nullable=False),
                    sa.Column('price', sa.Numeric(), nullable=False),
                    sa.Column('category', sa.String(
                        length=50), nullable=False),
                    sa.Column('description', sa.Text(), nullable=True),
                    sa.Column('dimensions', sa.String(
                        length=100), nullable=True),
                    sa.Column('weight', sa.String(length=40), nullable=True),
                    sa.Column('quantity', sa.Integer(), nullable=True),
                    sa.Column('image', sa.String(length=100), nullable=True),
                    sa.ForeignKeyConstraint(['sold_by'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('favorites',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=True),
                    sa.Column('product_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('purchases',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=True),
                    sa.Column('product_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('ratings',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=True),
                    sa.Column('product_id', sa.Integer(), nullable=True),
                    sa.Column('rating', sa.Numeric(), nullable=True),
                    sa.Column('comment', sa.String(length=250), nullable=True),
                    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('tags',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('product_id', sa.Integer(), nullable=True),
                    sa.Column('tag', sa.String(length=30), nullable=True),
                    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tags')
    op.drop_table('ratings')
    op.drop_table('purchases')
    op.drop_table('favorites')
    op.drop_table('products')
    op.drop_table('followers')
    op.drop_table('users')
    # ### end Alembic commands ###
