"""Update User

Revision ID: e20c5a29ab1f
Revises: 32047b6bd4af
Create Date: 2021-01-06 17:35:14.270944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e20c5a29ab1f'
down_revision = '32047b6bd4af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bio', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('money', sa.Numeric(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'money')
    op.drop_column('users', 'bio')
    # ### end Alembic commands ###
